### ISSUE TITLE
allow to not delete buffer

### ISSUE THREAD

**Issue by akabakass** [mei28/qfc.nvim#4]
The autoclose is interesting, but I rather not have the content of quickfix lost on close, maybe an option to disable delete will be interesting

**Comment by mei28** [comment]
Thank you for your comment.
Do you want to enable/disable the autoclose function later? Or do you prefer commands such as `:EnableQFC` or `:DisableQFC` in the command line?

Instead of setting it initially, if you want to configure it later, I can prepare specific commands for that. What do you think?

**Comment by mei28** [comment]
@akabakass 
Is the function in `#8de0a0712a28d128a7aea4b8945f6c2bc87da13e` in `addCmd` branch what you were looking for? I have added user commands that allow us to switch the enabled option at any time.

**Comment by akabakass** [comment]
oh sorry i mis-explained, though this is neat to have ;)
when the autoclose happen, it will empty the quickfix list at the same time, but i'd like to keep the content of it instead. i was thinking something like this:
```
{
      timeout = 3000,   -- Timeout setting in milliseconds
      enabled = true, -- Enable/disable autoclose feature
      empty_list_on_close = false -- empty quickfix list when autoclose
}
```
please tell me if i'm not clear, english is not my language

**Comment by mei28** [comment]
I think I understand what you mean. You want the quickfix (qf) window to auto-close when the qf list is empty and the window loses focus, but to remain open when there are items in the qf list.

When I originally created this plugin, my goal was to auto-close the qf window regardless of whether its list was empty or not, because in my coding style, having the window remain open was an obstacle :<.

However, your suggestion is useful, and I will consider how to implement it. If you can implement this, I would look forward to your PR!

**Comment by akabakass** [comment]
Nevermind, I think it was a bug and is fixed now, I don't see the problem anymore
Thx
